name = input("Enter your name: ")
address = input("Enter your address: ")
telephone_number = input("Enter your telephone number: ")
college_major = input("Enter your college major: ")
print(name)
print(address)
print(telephone_number)
print(college_major)
